services:
  - type: web
    name: geoacessivel
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn geoacessivel.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.11
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: WEB_CONCURRENCY
        value: "4"
